forum/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.viewIndex, name='forumindex'),
    path('create/', views.createPost.as_view(), name='createpost'),
    path('<int:pk>/', views.viewPost, name='viewpost'),
]

snifula/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('', TemplateView.as_view(
        template_name='snifula/index.html'), name='index'),
    path('users/', include('users.urls')),
    path('about/', views.aboutView, name='about'),
    path('forum/', include('forum.urls')),
    path('captcha/', include('captcha.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html',
                                                redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.registerView.as_view(), name='register'),
    path('<slug:username>/', views.profileView, name='profile'),
]

forum/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

from vote.models import *


class UserPost(VoteModel, models.Model):
    """User post"""

    # Essential info
    title = models.CharField(max_length=128)
    content = models.TextField()
    date_published = models.DateTimeField('Date Published', auto_now=True)

    # Author of the post in question
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    

    def __str__(self):
        return str(self.id)


class UserComment(VoteModel, models.Model):
    """User posted comment on a post"""

    # Add parents for the comment
    post = models.ForeignKey(UserPost, on_delete=models.CASCADE)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # Essential info
    content = models.TextField()
    date_published = models.DateTimeField('Date Published', auto_now=True)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

from django.utils import timezone


class Account(AbstractUser):
    """Override of Django's default user model"""

    # Some statistics
    posts = models.IntegerField('Num. of posts', default=0)
    comments = models.IntegerField('Num. of comments', default=0)
    score = models.IntegerField('Overall Score', default=0)
    date_joined = models.DateField('Date Joined', default=timezone.now)
    is_banned = models.BooleanField('Banned?', default=False)

    username = models.CharField(
        max_length=64, unique=True, db_index=True, primary_key=True)
    email = models.EmailField()

    def __str__(self):
        return self.username

forum/forms.py
from django import forms

from . import models


class AddUserPostForm(forms.ModelForm):
    """Form to add new UserPosts"""
    class Meta:
        model = models.UserPost
        fields = ('title', 'content')
        labels = {
            'title': 'Title',
            'content': '',
        }


class UserCommentForm(forms.ModelForm):

    class Meta:
        model = models.UserComment
        fields = ('content', )
        labels = {
            'content': '',
        }

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from captcha.fields import CaptchaField

from .import models


class AccountForm(UserChangeForm):
    """Custom Form to modify accounts"""
    captcha = CaptchaField()

    class Meta:
        model = models.Account
        fields = ('username', 'email', 'is_banned',)


class RegistrationForm(UserCreationForm):
    captcha = CaptchaField()

    class Meta(UserCreationForm.Meta):
        model = models.Account
        fields = ('username', 'email', )
        help_texts = {
            'username': 'max. 64 characters. (a-Z1-9_+-.)',
            'password2': None,
        }

forum/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import generic
from django.http.response import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_protect
import logging

import json
from . import forms
from . import models


@csrf_protect
def viewPost(request, pk):
    if request.method == 'POST':
        form = forms.UserCommentForm(request.POST)
        if form.is_valid() and not request.user.is_anonymous:
            post = get_object_or_404(models.UserPost, pk=pk)
            comment = models.UserComment(
                post=post, author=request.user, content=form.cleaned_data['content'])
            comment.save()
    post = get_object_or_404(models.UserPost, pk=pk)
    form_comment = forms.UserCommentForm
    return render(request, "forum/view.html", {"post": post, "commentform": form_comment})


@method_decorator(login_required, name='dispatch')
class createPost(generic.CreateView):
    model = models.UserPost
    form_class = forms.AddUserPostForm
    template_name = 'forum/create.html'
    success_url = reverse_lazy('postindex')

    def form_valid(self, form):
        newpost = form.save(commit=False)
        newpost.author = self.request.user
        newpost.save()
        return HttpResponseRedirect("/forum/" + str(newpost.id))


def viewIndex(request):
    keyword = request.GET.get('search', '')
    info = ''
    if keyword != '':
        info = "Seach results for: " + keyword
    posts = models.UserPost.objects.filter(
        title__contains=keyword).order_by('-date_published')
    return render(request, 'forum/index.html', {'posts': posts, 'searchinfo': info})

snifula/views.py
from django.views import View
from django.shortcuts import get_object_or_404, render

def aboutView(request):
    return render(request, 'snifula/about.html')

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.conf import settings

from . import models, forms


def profileView(request, username):
    user = get_object_or_404(models.Account, username=username)
    context = {'user': user}
    return render(request, "users/profile.html", context)


@login_required
def logoutView(request):
    logout(request)
    redirect(settings.LOGOUT_REDIRECT_URL)


class registerView(generic.CreateView):
    form_class = forms.RegistrationForm 
    success_url = reverse_lazy('login')
    template_name = 'users/register.html'

forum/templates/forum/create.html
{% extends 'base.html'%}


{% block title %}Create Post{% endblock %}
{% block content%}
	<h2>Submit a post</h2>
	{% if form.errors %}
	<p class="errortext">Creation of post failed</p>
	{% endif %}

	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">submit</button>
	</form>
{% endblock %}

forum/templates/forum/index.html
{% extends 'base.html'%}
{% load static %}
{% block title %}Forum{% endblock %}

{% block head %}
<script type="text/javascript">
	$('.votes_u').click(function(){

		var postid = $(this).attr("data-postid");
		$.ajax({
			type: 'POST',
			url: '/forum/upvote',
			data: {'postid': postid, 'csrftoken': '{{ csrf_token }}'},
			success: function(data){
				console.log(data)
			}
		});

	});
</script>
{% endblock %}
{% block content%}
<h2>{{ searchinfo }}</h2>
{% for post in posts %}
	<!--
			<button class="votes_u" data-postid="{{ post.id }}" id="u_{{ post.id }}"><img src="{% static 'forum/arrow_up_neutral.png' %}"></button>
			{{ post.votes.count }}
			<button class="votes_d" data-postid="{{ post.id }}" id="d_{{ post.id }}"><img src="{% static 'forum/arrow_down_neutral.png' %}"></button>
	--!>
	<p class="posttext"><a href="{%url 'viewpost' pk=post.id %}">{{post.title}}</a>, {{ post.date_published }} <span class="helptext">by <a href="{% url 'profile' username=post.author%}">{{post.author}}</a></span></p>
{% endfor %}

{% endblock %}

forum/templates/forum/view.html
{% extends 'base.html'%}

{% block title %}{{ post.title }}{% endblock %}

{% block content%}
<p class="helptext"><a href="/forum">Back</a></p>
<h2 id="title">{{ post.title }}</h2>
<p id="author" class="information">By <a href="{% url 'profile' username=post.author.username %}" style="text-decoration: none;">{{ post.author.username }}</a></p>
<p id="date" class="information">{{ post.date_published }}</p>
<p id="content">{{ post.content }}</p>
<hr>
<table id="comments" >
{% for comment in post.usercomment_set.all %}
	<tr>
	<th class="commentinfo">
		<p class="helptext" style="display: table-cell;">
		<a href="{% url 'profile' username=comment.author.username%}">{{ comment.author }}</a>
		{{ comment.date_published }}
		</p>
	</th>
	<th>
		<p style="text-align: left;"> {{ comment.content }}</p>	
	</th>
	</tr>
{% endfor %}
</table>
{% if user.is_authenticated %}
<form class="comment" action="{% url 'viewpost' pk=post.id %}" method="POST">
	{% csrf_token %}
	{{ commentform.as_p }}
	<input type="submit" value="comment"></input>
</form>
{% else %}
<p class="helptext">Please <a href="{% url 'login'%}?next={{request.path}}">login</a> to post comments</p>
{% endif%}
{% endblock %}

snifula/templates/base.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html>
	<head>
		<title>{% block title %}{% endblock %} - snifula.com</title>
		<link href='https://fonts.googleapis.com/css?family=Abel' rel='stylesheet'>
		<link href='https://fonts.googleapis.com/css?family=Abhaya+Libre' rel='stylesheet'>
		<link href='https://fonts.googleapis.com/css?family=Hind+Siliguri' rel='stylesheet'>
		<link rel="stylesheet" type="text/css" href="{% static "snifula/style.css"%}">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> 
		{%block head%}
		
		{% endblock %}
	</head>

	<body>
	
	<header>
		{% if user.is_authenticated %}
		<p><a href={% url 'createpost' %}>post</a> | <a href="{% url 'profile' username=user.username %}">{{ user.username }}</a> | <a href = "{%url 'logout' %}">logout</a></p>
		{% else %}
		<p><a href="{% url 'login' %}">Login</a> | <a href = "{%url 'register' %}">Register</a></p>
		{% endif %}
		<form action="{% url 'forumindex' %}" method="GET">
			<input name="search" type=search id="search">
			<button type="submit">search</button>
		</form>
		{% block header %}
		{% endblock %}
	</header>

	<main>	
		<a href="/" style="text-decoration: none; font-size: 50px;"><h1>snifula.com</h1></a>
			{% block main%}
			{% endblock %}
			<div id="content">
			{% block content %}

			{% endblock %}
			</div>
	</main>

	<footer>
		<p>Snifula.com &copy; 2018</p>
	</footer>
	</body>
</html>

snifula/templates/snifula/about.html
{% extends 'base.html'%}
{% load static %}
{% block title %}About{% endblock %}

{% block content %}
<h2>About Snifula.com</h2>
<p>Snifula.com is a forum site which was made as an experimental project and the current code for the website can be found on <a href="https://github.com/yrmyjaska/snifula">Github</a>. Snifula was designed to be quite minimal but many features are sure to come as the project progresses.</p>
<h2>Rules</h2>
<p>Anything can be posted on this site by anybody as long as they have an account to post with; However, there are  some limitations on what constitutes as 'anything'. The limitations are quite simple and anybody with common sense will understand them. <b>Any violation of these rules will result in a permanent ban from the site.</b></p>
<ul>
	<li>No illegal content/activities</li>
	<li>No spamming</li>
	<li>No spreading of harmful websites</li>
</ul>
<p>To re-iterate: anything goes as long as the content does not include or imply activities/content described above.</p>
{% endblock%}

snifula/templates/snifula/index.html
{% extends "base.html" %}

{% block title %} Snifula.com Index {% endblock %}

{% block content %}
<a href="/forum" style="text-decoration: none;"><p style="font-size:20px;">forum</p></a>
<a href="/about" style="text-decoration: none; "><p style="font-size:20px;">about</p></a>
{% endblock %}

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}Login{% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static "users/forms.css"%}">
{% endblock%} 

{% block header %}
{% endblock %}

{% block content %}
	<h2>Login</h2>
	{% if form.errors %}
	<p class="errortext">Invalid credientals!</p>
	{% endif %}
<form class="login" action="/users/login/" method="post">
	{% csrf_token %}
	<input type="hidden" name="next" value='{{ next }}'>
	{{ form.as_p }}
	<input type="submit" value="login">
</form>

{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
<h1>{{ user.username }}</h1>
<p>Member since {{ user.date_joined }}</p>
<p>Number of posts: <b>{{ user.userpost_set.count }}</b></p>
<p>Number of comments: <b>{{ user.usercomment_set.count }}</b></p>
<hr>
{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}
{% load static %}

{% block title %}Register{% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static "users/forms.css"%}">
{% endblock %}

{% block content %}
	<h2>Register</h2>
	{% if form.errors %}
		<p class="errortext">Invalid credientals! Please check again!</p>
	{% endif %}

	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">register</button>
	</form>
{% endblock %}